### ISSUE TITLE
Linux/Windows binaries for GiuChess 20190526

### ISSUE THREAD

**Issue by yellow-panther** [giuliano-ippoliti/GiuChess#1]
Hello Giuliano,
can you build Linux/Windows binaries (without bmi2) and host it on GitHub - subdirectory "releases" please? https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

A Mac OS compile by Julien Marcel from France (several years ago) is here: http://julien.marcel.free.fr/macchess/giuchess-10-beta2-ja-jm.zip

**Comment by giuliano-ippoliti** [comment]
Hello yellow-panther,

Sorry for replying so late. I've put the linux release in the releases/linux directory.
I'll put the Windows release soon!
Thanks for your interest for this old project :)

**Comment by giuliano-ippoliti** [comment]
Windows binary release too.
